### ISSUE TITLE
Mesclar RF05 com RF06

### ISSUE THREAD

**Issue by wdvictor** [wdvictor/Git-Breakdown-mobile#16]
RF05 e RF06 podem ser feitas dentro da mesma página e com a mesma requisição, então não já necessidade de duas RF's ou 2 milestones

**Comment by baraky** [comment]
O PR da #6 precisa da conclusão dessa issue.

**Comment by baraky** [comment]
Milestones e [Wiki](https://aprender3.unb.br/mod/wiki/view.php?pageid=820) atualizadas. Issue concluída.
